- name: install nginx
  hosts: frontend
  tasks:
  - name: nginx install
    ansible.builtin.package:
    - name: nginx
      state: installed
  - name: start nginx
    ansible.builtin.service:
    - name: nginx
      state: started
      enable: yes
