- name: install nginx and start
  hosts: frontend
  tasks:
  - name: nginx install
    ansibles.builtin.package:
    - name: nginx
      state: present      
  - name: start nginx
    ansible.builtin.service:
    - name: nginx
      state: started
      enable: yes
