- name: play level variables
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: loops install
    ansible.builtin.dnf:
     name: {{item}}
     state: installed
    loop:
    - nginx
    - mysql
    - zip
