- name: functions
  hosts: local
  connection: local
  become: yes
  vars:
   technologies: DevOps, Linux, Shell, Ansible
   name: "Murali Challa"
   email: "MKREDDY23@gmail.com"
   ipaddress: "10.0.0.0"
   tags:
    Application: Payment
    Environment: Dev
   listtags:
   - key: Application
     value: Payment
   - key: Environment
     value: Dev
  tasks:
  - name: split function
    ansible.builtin.debug:
     msg: " Technologies are: {{technologies | split(',') }}"

  - name: map/distionary to list
    ansible.builtin.debug:
     msg: "Tags are : {{ tags | dict2items }}"

  - name: list to map/distionary
    ansible.builtin.debug:
     msg: "listtags are : {{ listtags | items2dict }}"

  - name: read yaml and store in variable
    ansible.builtin.set_fact:
     file_yaml: "{{ lookup('file','student.yaml') | from_yaml }}"

  - name: print student yaml
    ansible.builtin.debug:
     msg: " yaml read: {{file_yaml | to_json }}"

  - name: Save file to json
    ansible.builtin.copy:
     dest: ./student-data.json
     content:  "{{file_yaml | to_nice_json }}"

  - name: upper and lower
    ansible.builtin.debug:
     msg: "{{ name | upper }}"

  - name: upper and lower
    ansible.builtin.debug:
     msg: "{{ email | lower }}"
  
  - name: check ip is valid or not
    ansible.builtin.debug:
     msg: "{{ ipaddress  | ansible.utils.ipv4 }}"