- name: functions
  hosts: local
  connection: local
  become: yes
  vars:
   technologies: DevOps, Linux, Shell, Ansible
   tags:
    Application: Payment
    Environment: Dev
  tasks:
  - name: split function
    ansible.builtin.debug:
     msg: " Technologies are: {{technologies | split(',') }}"

  - name: map/distionary to list
    ansible.builtin.debug:
     msg: "Tags are : {{ tags | dict2items }}"